# Generated by Django 3.2.8 on 2021-11-05 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('people_type', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('meeting_date', models.DateField()),
                ('meeting_starttime', models.DateTimeField()),
                ('meeting_end_time', models.DateTimeField()),
                ('room_set', models.ManyToManyField(to='meeting.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
                ('user_set', models.ManyToManyField(related_name='guest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
